/**
 * GitHub Integration for ICS-218 Forms
 * 
 * Creates GitHub issues for ICS 218 Support Vehicle/Equipment Inventory submissions.
 * Each form creates a tracking issue with:
 * - Incident information
 * - Vehicle summary
 * - PDF link
 * - Prepared by information
 */

import type { Env } from '../index';

interface ICS218Vehicle {
  orderRequestNumber?: string;
  incidentIdNo?: string;
  classification: string;
  make: string;
  categoryKindType: string;
  features?: string;
  agencyOwner: string;
  operatorNameContact: string;
  vehicleLicenseId: string;
  incidentAssignment: string;
  startDateTime: string;
  releaseDateTime?: string;
  airtableId?: string;
}

interface ICS218FormData {
  id: string;
  incidentName: string;
  incidentNumber: string;
  datePrepared: string;
  timePrepared: string;
  vehicleCategory: string;
  vehicles: ICS218Vehicle[];
  preparedBy: {
    name: string;
    positionTitle: string;
    signature: string;
    signatureTimestamp: string;
  };
  submittedAt: string;
  submittedBy: string;
}

const REPO_OWNER = 'FLTF2-USAR';
const REPO_NAME = 'usar-ics212-system';

/**
 * Create GitHub issue for ICS 218 form submission
 * 
 * @param env - Cloudflare Worker environment with GITHUB_TOKEN
 * @param formData - ICS 218 form data
 * @param pdfUrl - URL to generated PDF in R2 storage
 * @returns GitHub issue number
 */
export async function createICS218GitHubIssue(
  env: Env,
  formData: ICS218FormData,
  pdfUrl?: string
): Promise<number> {
  const title = `[ICS 218] ${formData.incidentName} - ${formData.vehicleCategory} - ${new Date(formData.datePrepared).toLocaleDateString()}`;

  // Build vehicle summary
  const vehicleSummary = formData.vehicles
    .map((v, idx) => 
      `${idx + 1}. **${v.make}** (${v.classification}) - License: ${v.vehicleLicenseId} - ${v.incidentAssignment}`
    )
    .join('\n');

  // Build issue body
  const issueBody = `# ICS 218 Support Vehicle/Equipment Inventory

**Form ID**: \`${formData.id}\`  
**Incident**: ${formData.incidentName}  
**Incident Number**: ${formData.incidentNumber}  
**Date Prepared**: ${new Date(formData.datePrepared).toLocaleDateString()} ${formData.timePrepared}  
**Vehicle Category**: ${formData.vehicleCategory}

${pdfUrl ? `\n📄 **[Download Official PDF](${pdfUrl})**\n` : ''}

## Vehicle Summary

**Total Vehicles**: ${formData.vehicles.length}

### Vehicles Listed

${vehicleSummary}

## Vehicle Details

${formData.vehicles.map((v, idx) => `
### Vehicle ${idx + 1}: ${v.make} (${v.classification})

- **Order Request #**: ${v.orderRequestNumber || 'N/A'}
- **Incident ID #**: ${v.incidentIdNo || 'N/A'}
- **Category/Type**: ${v.categoryKindType}
- **Features**: ${v.features || 'None listed'}
- **Agency/Owner**: ${v.agencyOwner}
- **Operator**: ${v.operatorNameContact}
- **License/ID**: ${v.vehicleLicenseId}
- **Assignment**: ${v.incidentAssignment}
- **Start Date/Time**: ${new Date(v.startDateTime).toLocaleString()}
- **Release Date/Time**: ${v.releaseDateTime ? new Date(v.releaseDateTime).toLocaleString() : 'Not released'}
${v.airtableId ? `- **Airtable Record**: ${v.airtableId}` : ''}
`).join('\n')}

## Prepared By

**Name**: ${formData.preparedBy.name}  
**Position**: ${formData.preparedBy.positionTitle}  
**Signature**: ✅ Digital signature captured  
**Timestamp**: ${new Date(formData.preparedBy.signatureTimestamp).toLocaleString()}

## Submission Info

**Submitted At**: ${new Date(formData.submittedAt).toLocaleString()}  
**Submitted By**: ${formData.submittedBy}

---
*Auto-generated by USAR ICS Forms System*
`;

  // Labels for the issue
  const labels = [
    'ics-218',
    'vehicle-inventory',
    formData.vehicleCategory.toLowerCase().replace(/\s+/g, '-'),
    formData.incidentName.toLowerCase().replace(/\s+/g, '-'),
  ];

  // Create GitHub issue
  const githubUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues`;

  const response = await fetch(githubUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'User-Agent': 'USAR-ICS-Forms-System',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title,
      body: issueBody,
      labels,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`GitHub API error: ${response.status} ${errorText}`);
  }

  const issue = await response.json();
  console.log(`Created GitHub issue #${(issue as any).number} for ICS 218 form ${formData.id}`);
  
  return (issue as any).number;
}

/**
 * Add comment to existing ICS 218 GitHub issue
 * 
 * @param env - Cloudflare Worker environment
 * @param issueNumber - GitHub issue number
 * @param comment - Comment text
 */
export async function addICS218IssueComment(
  env: Env,
  issueNumber: number,
  comment: string
): Promise<void> {
  const githubUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues/${issueNumber}/comments`;

  const response = await fetch(githubUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'User-Agent': 'USAR-ICS-Forms-System',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ body: comment }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`GitHub API error: ${response.status} ${errorText}`);
  }

  console.log(`Added comment to ICS 218 issue #${issueNumber}`);
}
